version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install node depedencies
          command: yarn
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: CI=false yarn build
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/python:latest
    steps:
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install dependencies
          command: sudo pip install awscli
      - run:
          name: show me all the files in workspace
          command: ls .
      - run:
          name: Deploy to S3
          command: aws s3 cp --recursive ~/project/build s3://william-lee.com/

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
